from torch import rand

TEST_INPUTS = {"AUDIO_DIR_TEST": [{"audio_dir": r"test_resources/dx7"}],
               "CONVBLOCK_TEST": [{"n_in": 10,
                                   "n_hidden": 10,
                                   "batchnorm_flag": False,
                                   "dropout_flag": False,
                                   "test_tensor": rand(10, 10)},
                                  {"n_in": 10,
                                   "n_hidden": 10,
                                   "batchnorm_flag": True,
                                   "dropout_flag": True,
                                   "test_tensor": rand(10, 10)}
                                  ],
               "RESBLOCK_TEST": [{"n_in": 10,
                                  "n_depth": 2,
                                  "dilation_growth_rate": 2,
                                  "dilation_cycle": None,
                                  "reverse_dilation": False,
                                  "m_conv": 1,
                                  "test_tensor": rand(10, 10)},
                                 {"n_in": 10,
                                  "n_depth": 6,
                                  "dilation_growth_rate": 4,
                                  "dilation_cycle": None,
                                  "reverse_dilation": True,
                                  "m_conv": 2,
                                  "test_tensor": rand(10, 10)}
                                 ],
               "ENCODERBLOCK_TEST": [{"input_emb_width": 10,
                                      "output_emb_width": 5,
                                      "down_t": 2,
                                      "stride_t": 2,
                                      "width": 10,
                                      "depth": 3,
                                      "m_conv": 1,
                                      "dilation_growth_rate": 3,
                                      "dilation_cycle": None,
                                      "zero_out": False,
                                      "res_scale": False,
                                      "dropout": 0.0,
                                      "test_tensor": rand(10, 10)},
                                     {"input_emb_width": 1000000,
                                      "output_emb_width": 10,
                                      "down_t": 3,
                                      "stride_t": 2,
                                      "width": 10,
                                      "depth": 20,
                                      "m_conv": 2,
                                      "dilation_growth_rate": 5,
                                      "dilation_cycle": 1,
                                      "zero_out": True,
                                      "res_scale": False,
                                      "dropout": 0.3,
                                      "test_tensor": rand(1000000, 10)}
                                     ],
               "DECODERBLOCK_TEST": [{"input_emb_width": 500,
                                      "output_emb_width": 5,
                                      "down_t": 2,
                                      "stride_t": 2,
                                      "width": 10,
                                      "depth": 3,
                                      "m_conv": 1,
                                      "dilation_growth_rate": 3,
                                      "dilation_cycle": None,
                                      "zero_out": False,
                                      "res_scale": False,
                                      "dropout": 0.0,
                                      "reverse_dilation": True,
                                      "test_tensor": rand(5, 10)},
                                     {"input_emb_width": 10000,
                                      "output_emb_width": 10,
                                      "down_t": 3,
                                      "stride_t": 2,
                                      "width": 100,
                                      "depth": 2,
                                      "m_conv": 2,
                                      "dilation_growth_rate": 5,
                                      "dilation_cycle": 1,
                                      "zero_out": True,
                                      "res_scale": False,
                                      "dropout": 0.3,
                                      "reverse_dilation": True,
                                      "test_tensor": rand(10, 10)}
                                     ],
               "ENCDEC_TEST": [{"input_emb_width": 5000,
                                "output_emb_width": 5,
                                "down_t": 3,
                                "stride_t": 2,
                                "width": 8,
                                "depth": 3,
                                "m_conv": 1,
                                "dilation_growth_rate": 3,
                                "dilation_cycle": None,
                                "zero_out": False,
                                "res_scale": False,
                                "batchnorm_flag": True,
                                "dropout": 0.0,
                                "reverse_dilation": True,
                                "test_tensor": rand(5000, 64)},
                               {"input_emb_width": 1000,
                                "output_emb_width": 10,
                                "down_t": 4,
                                "stride_t": 1,
                                "width": 100,
                                "depth": 2,
                                "m_conv": 2,
                                "dilation_growth_rate": 5,
                                "dilation_cycle": 1,
                                "zero_out": False,
                                "batchnorm_flag": True,
                                "res_scale": False,
                                "dropout": 0.3,
                                "reverse_dilation": True,
                                "test_tensor": rand(1000, 64)}
                               ]
               }
